[theme]
base="light"
primaryColor= "#3457d8"

[[pages]]
path = "app_aves.py"
name = "Inicio"
icon = "ğŸ "

[[pages]]
path = "identificador.py"
name = "Identificador de Aves"
icon = "ğŸ”"

[[pages]]
path = "visualizador.py"
name = "Visualizador de Aves"
icon = "ğŸŒ"